### ISSUE TITLE
Fixes in Ndp class not reflected in Sedeen class

### ISSUE THREAD

**Issue by SamuelHLam** [waynewccheng/autohotkey#18]
The function 'mycomp' was fixed for Ndp, but the same errors still exist in the Sedeen class (images not trimmed correctly).

The SKIP_UPDATE parameter should be environment-dependent. Is there a way to turn off Sedeen auto-checking for updates upon launch? That would make the parameter unnecessary and the code more robust.

**Comment by waynewccheng** [comment]
Is there a way to turn off Sedeen auto-checking for updates upon launch? That would make the parameter unnecessary and the code more robust.

That's a good idea. Do you know how to do it?

I will modify SKIP_UPDATE as a user-dependent variable

**Comment by SamuelHLam** [comment]
Error thrown in newest commit:

Unrecognized property 'SEDEEN_SKIP_UPDATE' for class 'Ndp'.

Error in Viewer (line 45)
                obj.SEDEEN_SKIP_UPDATE = 0;

Error in Ndp

Error in demo_0603 (line 1)
n = Ndp
